### ISSUE TITLE
QUESTION: Can you make this 182 into a RG?

### ISSUE THREAD

**Issue by CA1012** [HHS81/c182#101]
The new cessna 182RGs are really cool to train in for complex aircraft training and i was hoping you could add the RG in as a sub-model

**Comment by gilbertohasnofb** [comment]
What do you mean by "new" 182RG model? As far as I know, the RG model was produced between  1978 and 1986. They are a completely different model than ours, which is two decades younger (including a completely different panel and interior), so making a RG variant would mean creating a completely new project rather than making just a few modifications. I also like the RG very much, but I find it unlikely to happen from this project; I believe @HHS81 probably agrees with me here, right?

**Comment by HHS81** [comment]
Indeed, the Cessna 182 RG isn't new and not in production any more. 
And both models are completely different: shorter nose, gear bays, different landinglights.... Well, that is the easiest part since we have already a shorter c182 modelled.

But the interior ist really different, and the systems are more complex. I would really like to see a Turbo RG, but as Gilberto said, it is a completly different aircraft and currently I don't see that I have any spare time left to change this.

**Comment by gilbertohasnofb** [comment]
@HHS81 If this is a `wontfix` then I will close the issue, ok?
