### ISSUE TITLE
re-UV map seats

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#18]
Re-UV map seats: currently all four seats are identical models, but they are mapped into a 2048x2048 texture. And unfortunately, like #2, the UV-map isn't really perfectly symmetrical... 

Proposed solution: use a single 1024x1024 texture for all four seats. If you accept that, please use this paintkit (which is just the top left corner of your paintkit) and this texture as reference, Heiko, as I have already finished the seat textures:

![paneltexturing-seats-new-paintkit](https://cloud.githubusercontent.com/assets/5700795/12024759/df3f68fa-ada7-11e5-963b-c10096854128.png)

![paneltexturing-seats-new](https://cloud.githubusercontent.com/assets/5700795/12024763/eda1e2b0-ada7-11e5-801a-851272dec786.png)

**Comment by gilbertohasnofb** [comment]
Resulting in this:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/12024772/00db38fe-ada8-11e5-9c7c-28a6da3d538d.png)

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/12024775/08b17c8c-ada8-11e5-94a6-8c71e4b650c7.png)

**Comment by HHS81** [comment]
They are not really identical models. The back ones are indeed a bit different as they has a different height.(like in real)

It was my intention to do it like that: I plan to use lightmaps for the whole cabin. A single UVmap used for all four seats will make the look of the lighting wrong and unrealistic.  
I see also you used alpha channel on the textures for the seatframe. Alpha channels are always framerate killers and for Rembrandt an application of the transparent-eff.file is needed. 

I didn't modelled the seatframe since I never found any pictures of it. The only one I found is this: http://www.chicagolandaviation.com/wp-content/uploads/2015/03/N510TR-Cessna-182T-Interior11.jpg

But I can model the frame according your texture file and map it.
Otherwise it looks great, photorealistic, like real leather!

**Comment by gilbertohasnofb** [comment]
I see, so let's make it like this:

- I will remove the alpha channel and simply make a dark square so when you create the new model for the seat frame the textures will be ready
- I will then create the four textures for each individual seat, no problems
- let's close this issue then and open a new one for the new model of the seat frames

As for the reference for the seat frame, I have this picture here (not sure if it is from your zip or if I got somewhere else on the internet):

![n67mr_15](https://cloud.githubusercontent.com/assets/5700795/12025723/ecfeae9c-adb1-11e5-9780-c3f741797432.jpg)

Else we can use something generic like the c172p, which is already better than a simple rectangle. In the texture below, the seat frame is in the bottom right, and its left side is what touchs the ground:

![](https://raw.githubusercontent.com/Juanvvc/c172p-detailed/master/Models/interior.png)

What do you say?

**Comment by HHS81** [comment]
After a long research I don't finy any reference images. So I will use the one from the C172p.

**Comment by gilbertohasnofb** [comment]
Sounds reasonable to me, and if later we come across some better reference image we can then do something about it.
