### ISSUE TITLE
Make the normalmap more subtle

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#28]
What about making the normalmap a bit more subtle? These images ![here](https://github.com/HHS81/c182/issues/23#issuecomment-170189033) look stunning, but I feel that in RL the 182 is not that reflective and you can't see the rivets so easily. What do you say if we tune this effect a little bit down, @HHS81?

**Comment by HHS81** [comment]
I know that the effect is exaggerated, this is currently needed to check if all rivets  and lines sits at the right point - and of course to show that I have worked on the model ;-). ( There are still some lines and rivets missing, and a specularity map is also missing yet). 

The Paintkit I have in work already allows to control the opacity of each layer containing rivets and lines, so the appearence can be changed. Also the strength of reflection can be adjusted by user in each livery.xml-files. I'm planning to use the dirt effect of the shader, so with more and more flight hours more dirt will be visible.....

The problem is and will be, that our shader doesn't allow 
a.) fresnel effect
and
b.) the way the reflection is blended with the texture underneath might be not correct for a coated surface. Something I have to discuss with someone with shader knowledge.

About wrinkles etc...I'm still experimenting, but didn't found any way to make them look realistic. As wrinkles also affects reflection we would need a vertex-shader, but this will cost fps....Such effects like we can see on the wings bottom we can't currently achieve: http://www.avsim.com/pages/1112/Carenado/Pg_2Cessna%20Aircraft%20co%20-%20Photo1.JPG

But gooneybirds approach looks nice, but as he also found out since the reflection is not influenced by the painted wrinkles, the effect is diluted. 

Even this I wasn't able to create yet: http://www.flightsim.com/images/reviews/carct182/2013-9-30_17-40-8-508.jpg

Btw. I'm really thinking of adding the C182 T-Variant, but needs some changes of the cabin, and a good G1000.....

**Comment by HHS81** [comment]
Btw.(@Johan G.) the C182 doesn't have flushed rivets: http://www.flyperformance.com/wp-content/uploads/2015/05/N182FN-12.jpg
http://www.flyperformance.com/wp-content/uploads/2015/05/N182FN-28.jpg

And yes, a fresh cleaned aircraft is quite reflective: http://www.flyperformance.com/wp-content/uploads/2015/05/N182FN-20.jpg

**Comment by gilbertohasnofb** [comment]
> I know that the effect is exaggerated, this is currently needed to check if all rivets and lines sits at the right point - and of course to show that I have worked on the model ;-)

Good to know!

>  Also the strength of reflection can be adjusted by user in each livery.xml-files

That's very handy.

> About wrinkles etc...I'm still experimenting, but didn't found any way to make them look realistic [...] gooneybirds approach looks nice, but as he also found out since the reflection is not influenced by the painted wrinkles, the effect is diluted. 

Yes, looking at his pictures the effect is quite diluted IMO as well. As for that Carenado image from avsim, I can't access Avsim for some reason, I will try later... 

>  I'm really thinking of adding the C182 T-Variant, but needs some changes of the cabin, and a good G1000.....

Sounds like fun (and like a ton of work!) :smile: 

> Btw.(@Johan G.)

I will forward it to the forum as he won't receive notifications of your reply here.

**Comment by HHS81** [comment]
And just for clarification: "The way to do that is that, we create an extremely high polygon 3D model with all the details, including but not limit to imperfect surfaces, rivets, and everything... Then, we bake a normal map, and then, we apply it to the low polygons 3D model. I can do that if we start to make a more detailed 3D model." (http://forum.flightgear.org/viewtopic.php?f=4&t=21965&start=615#p272326)

No, that's just one way, which indeed gives a quite nice details. But usually you can create it even without: http://www.katsbits.com/tutorials/textures/how-not-to-make-normal-maps-from-photos-or-images.php

I won't start to create a very high detailed model again just for a nomalmap!

**Comment by gilbertohasnofb** [comment]
You are spot on.

**Comment by HHS81** [comment]
Quote by wkitty from forum: "no response for my post about not wanting rivets or even shiny chrome engine rings?? is there no other way than to completely redo the blend/ac file(s) to remove those undesirable artifacts???"

What is he talking about? There are no shiny crome engine rings, and if he don't want rivets he must simply disable the norma/ bumplmap effect via the rendering settings.

**Comment by gilbertohasnofb** [comment]
You tell me. I answered him though, together with your answer above.

**Comment by HHS81** [comment]
Normalmap effect more subtle, shininess of the aicraft can be defined in each livery file, reflection strength as well, and the upcoming paintkit will allow to set the strength of each layer. Issue closed

**Comment by gilbertohasnofb** [comment]
Heiko, I have to say that the aircraft look now completely non-shinny to me, is that intentional for the three liveries you created? I personally feel that the plane looked much better before.

**Comment by HHS81** [comment]
Can you tell me, when it looked better?

You can controll the shininess now dynamically  (with property browser even in runtime) per each livery in the livery-file.xml:

` <specular>
		<red>0.75</red>
		<green>0.75</green>
		<blue>0.75</blue>
</specular>`

and the reflection strength by 

`<refl_correction type="string">-0.3</refl_correction>`

**Comment by gilbertohasnofb** [comment]
I think that in this image the normal map is a tiny bit too shiny, but it was better than what we have now IMO:

![](https://cloud.githubusercontent.com/assets/12649375/12214233/f82ced6e-b68b-11e5-8667-69edcc6fe377.jpg)

I have the impression that when we made it more subtle, it actually become too subtle if you know what I mean. I can try to play around with those values if you want, but given that these liveries are yours maybe you want to set it to a value you like yourself :wink:

**Comment by gilbertohasnofb** [comment]
It's just that now all three liveries look completely "washed out", almost only white on white regardless of shadows and illumination.

**Comment by HHS81** [comment]
Wait until I have the paintkit ready. 

There are four things which influence the appearence of the rivets, and three of them can changed by the user each per livery:

- the strength of the rivets itself by the paintkit
- the strength of the reflection
- the strength of the shininess (specular effect)

-the strength of the normalmap  unfortunately can't be changed by the user

**Comment by gilbertohasnofb** [comment]
Okay, so I suggest we leave this issue opened but tackle it later once the paintkit is done. What do you say?

**Comment by HHS81** [comment]
@gilbertohasnofb can this be closed?

**Comment by gilbertohasnofb** [comment]
:+1:
