### ISSUE TITLE
rethink the texture of the leather in the top panel

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#88]
Rethink the texture of the leather in the top panel: if we UV map the whole top panel as of now, it's impossible to get a high resolution leather texture. I would love to achieve this sort of detail here:

![](https://flyawaysimulation.com/media/images14/images/a2a-cessna-182-cockpit.jpg)

What about using some sort of grain texture that is tileable just for that object, would that work? Do you have some idea on how to deal with it, @HHS81?

**Comment by HHS81** [comment]
When I started the UVMap I had the  impression from the existing images I had, that the glareshield is made of some form of smooth plastic. I didn't see any leather textures, so I decided to have this in this size. 
Myself isn't very happy now with that, but to re-sort the existing textures is much too much work.
I thought about adding a amphibian version later using the model and texture of the c172p. The texture of the floats I planned to be extend for baggage textures, RBF, and the red-white-thing in the left bag in the oicture above and other stuff (the static objects were originally planed there as well), so maybe this can be used for. And it would be o.k, for a later Cessna (T)182T-variant, since they would share those texture.

**Comment by gilbertohasnofb** [comment]
That all sounds okay with me. I may try to change the top panel texture we have now for something different: right now we are using a generic leather texture, but in this A2A example above we can see it's actually some rugged plastic. I will try replacing it with a dark texture + very fine grain to it and see if it looks better. I will keep you updated about it.

**Comment by gilbertohasnofb** [comment]
Hmm, this is the best I can do, the resolution just isn't there:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/13089369/9328edfe-d4f0-11e5-924e-45a1559e11dd.png)

What about this: what if on the top left corner of PanelTexturing-Interior.png we have a 300x300 black plastic tile which will be applied multiple in Blender, instead of a texture for the whole top panel? Would you like to try that?

**Comment by HHS81** [comment]
I'm not sure how it will interact with AOMaps or lightmaps. I have to test
